// API
export const SET_LOADING_STATE = 'SET_LOADING_STATE';

// Auth
export const INIT_APP = 'INIT_APP';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';

// User
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_UP_AND_UPDATE_PROFILE = 'USER_SIGN_UP_AND_UPDATE_PROFILE';
export const USER_RESEND_VERIFICATION_EMAIL = 'USER_RESEND_VERIFICATION_EMAIL';
export const USER_VERIFY_EMAIL = 'USER_VERIFY_EMAIL';
export const USER_PROFILE = 'USER_PROFILE';
export const USER_SET_PROFILE = 'USER_SET_PROFILE';
export const USER_SET_ERROR = 'USER_SET_ERROR';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const START_RESET_PASSWORD = 'START_RESET_PASSWORD';
export const CHECK_RESET_PASSWORD_TOKEN = 'CHECK_RESET_PASSWORD_TOKEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SET_RESET_PASSWORD_TOKEN_VALID = 'SET_RESET_PASSWORD_TOKEN_VALID';

// Search
export const SEARCH_INITIAL_LOAD = 'SEARCH_INITIAL_LOAD';
export const SEARCH_SET_INDUSTRIES = 'SEARCH_SET_INDUSTRIES';
export const SEARCH_SET_FIELDS_UPDATE_HASH = 'SEARCH_SET_FIELDS_UPDATE_HASH';
export const SEARCH_SET_RESULT_FILTERS = 'SEARCH_SET_RESULT_FILTERS';
export const SEARCH_DROPDOWN = 'SEARCH_DROPDOWN';
export const SEARCH_FIELDS = 'SEARCH_FIELDS';
export const SEARCH_GET_NEXT_PAGE = 'SEARCH_GET_NEXT_PAGE';
export const SEARCH_SET_PAGINATION = 'SEARCH_SET_PAGINATION';
export const SEARCH_SET_PRISTINE = 'SEARCH_SET_PRISTINE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

// Explorer
export const EXPLORER_GET_DISTINCT_INDUSTRIES = 'EXPLORER_GET_DISTINCT_INDUSTRIES';
export const EXPLORER_GET_DISTINCT_INDUSTRIES_PREVIEW = 'EXPLORER_GET_DISTINCT_INDUSTRIES_PREVIEW';
export const EXPLORER_SET_LISTS_INDUSTRY = 'EXPLORER_SET_LISTS_INDUSTRY';
export const EXPLORER_INDUSTRY_TREE = 'EXPLORER_INDUSTRY_TREE';
export const EXPLORER_INDUSTRY_SEARCH_ITEMS = 'EXPLORER_INDUSTRY_SEARCH_ITEMS';
export const EXPLORER_SET_PUBLISHERS = 'EXPLORER_SET_PUBLISHERS';
export const EXPLORER_SET_METRICS = 'EXPLORER_SET_METRICS';
export const EXPLORER_SET_SEGMENTATIONS = 'EXPLORER_SET_SEGMENTATIONS';
export const EXPLORER_SET_OVERVIEW = 'EXPLORER_SET_OVERVIEW';

// Company
export const COMPANY_GET_SEARCH_ITEMS = 'COMPANY_GET_SEARCH_ITEMS';
export const COMPANY_GET_SEARCH_ITEMS_SUCCESS = 'COMPANY_GET_SEARCH_ITEMS_SUCCESS';
export const COMPANY_GET = 'COMPANY_GET';
export const COMPANY_GET_SUCCESS = 'COMPANY_GET_SUCCESS';
export const COMPANY_ERROR = 'COMPANY_ERROR';
